baseurl = "https://yingw787.github.io/traveltile_docs"
languageCode = "en-us"
title = "Traveltile Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Ying Wang"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/yingw787/traveltile_opensrc"

	version = "0.5.0"
	logo = "images/logo.png"
	favicon = "favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "indigo"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "yingw787"
	email   = "yingw787@gmail.com"


[[menu.main]]
	name   = "Traveltile"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 15

[[menu.main]]
	name   = "Viewing content"
	url    = "viewing-content/"
	weight = 17.5

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 20

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 25


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
